### PR TITLE
Update init.lua

### PR DESCRIPTION
**Pull request by LeoLeg2009**
Update please :)

### CODE REVIEW

**Comment by markopetrovi** [comment]
This pull request appears to be trying to change the code of mcl_nether to require less resources for crafting **mcl_nether:netherite_ingot** and **mcl_nether:netheriteblock**.
Such game-altering modification would need to be approved through the vote by Mineclone players and staff before it gets merged.

As for now, the change:
```
minetest.register_craft({
	output = "mcl_nether:netherite_ingot 9",
	recipe = {
		{"mcl_nether:netheriteblock", "", ""},
-		{"", "", ""},
+		{"", "", ""}
		{"", "", ""}
	}
})
```
introduces a syntax error, since entries in the recipe table have to be comma separated. Until that is solved, the pull request can't be merged due to having a syntax error in the first place.

**Comment by LeoLeg2009** [comment]
@markopetrovi i'm sorry for forget the comma :/ but it's not a such changement, just a little

**Comment by LeoLeg2009** [comment]
@markopetrovi i added the comma, can you accept pleas <:(

**Comment by LeoLeg2009** [comment]
> @markopetrovi i added the comma, can you accept pleas <:(

**Comment by LeoLeg2009** [comment]
wrong button…

**Pull request closed without merging**
